### ISSUE TITLE
Still Active?

### ISSUE THREAD

**Issue by jasonkonopacki** [shiftplanning/php-sdk#6]
Is this API still active? 
Every time I attempt to connect, I get a response of "The ShiftPlanning API is not responding."

**Comment by traykovn** [comment]
Same here

**Comment by mar1ja** [comment]
Hello,

I was having the same issue and I figured it out, it's SSL, this helped me:
curl_setopt( $ch, CURLOPT_SSL_VERIFYPEER, FALSE);

**Comment by fanzila** [comment]
Working fine with me
